#  Oracle에 필요한 패키지 설치
yum -y update
yum install -y binutils compat-libcap1 gcc gcc-c++ glibc glibc glibc-devel glibc-devel ksh compat-libstdc++-33 libaio libaio libaio-devel libaio-devel libgcc libgcc libstdc++ libstdc++ libstdc++-devel libstdc++-devel libXi libXi libXtst libXtst make sysstat xorg-x11-apps

# Oracle 계정의 필요한 그룹과 유저를 생성
groupadd oracle
groupadd dba
useradd -g oracle -G dba oracle
passwd oracle
oracle
oracle

# Oracle Base가 되는 디렉토리 생성 후 권한 부여
cd /home/oracle
mkdir db
chown -R oracle:oracle db
chmod -R 775 db
chmod g+s db

# Oracle 계정의 환경 변수 설정을 위한 편집기 실행, .bash_profile의 맨 아래 Line에 입력
vi /home/oracle/.bash_profile
export TMP=/tmp
export TMPDIR=/tmp
export ORACLE_BASE=/home/oracle/db
export ORACLE_SID=orcl
export ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome_1
export ORACLE_HOME_LISTNER=$ORACLE_HOME/bin/lsnrctl
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH=$ORACLE_HOME/bin:$PATH
export NLS_LANG=KOREAN_KOREA.AL32UTF8

ORACLE_HOME=

# 커널 설정을 하기 위해 /etc/sysctl.conf 편집, 맨 아래 Line에 입력
vi /etc/sysctl.conf
fs.aio-max-nr = 1048576
fs.file-max = 6815744
kernel.shmall = 2097152
kernel.shmmax = 1987162112
kernel.shmmni = 4096
kernel.sem = 250 32000 100 128
net.ipv4.ip_local_port_range = 9000 65500
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048586

# 커널 수정한 내용 적용 및 확인
sysctl -p

# Oracle 계정의 Shell limit를 설정 하기 위해 /etc/security/limits.conf 편집
vi /etc/security/limits.conf
oracle soft nproc 2047
oracle hard nproc 16384
oracle soft nofile 1024
oracle hard nofile 65536

# Oracle Site에서 다운받은 Oracle 설치파일을 unzip으로 해제 후 Oracle 계정으로 접속
unzip linuxx64_12201_database.zip
su - oracle
cd /home/oracle/database

# Oracle 실행하기
./runinstaller

# GUI 화면 구성을 위한 실행
su root
1234
export DISPLAY=:0.0
echo DISPLAY
xhost +
xclock
su - oracle
oracle
export DISPLAY=:0.0
echo DISPLAY
xhost +
xclock

# GUI 화면 실행 후 설정 단계
# .
# .
# .

# 새로운 터미널 열고 root 계정으로 sh 파일 실행
/home/oracle/oraInventory/orainstRoot.sh
/home/oracle/db/product/12.1.0/dbhome_1/root.sh
# 엔터엔터엔터

# GUI를 통한 Oracle 설치 완료
su - oracle
sqlplus -version
sqlplus / as sysdba

# 인스턴스 시작/중지
sqlplus '/as sysdba'
startup
shutdown

# 리스너 시작/중지
lsnrctl start
lsnrctl stop

# listener.ora Network Configuration File: /home/oracle/db/product/12.1.0/dbhome_1/network/admin/listener.ora
# Generated by Oracle configuration tools.

LISTENER =
 (DESCRIPTION_LIST =
  (DESCRIPTION =
   (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.2.44)(PORT = 1521))
   (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
  )
 )

SID_LIST_LISTENER =
  (SID_LIST =
   (SID_DESC =
    (ORACLE_HOME = /home/oracle/db/product/12.1.0/dbhome_1)
    (SID_NAME = orcl)
 )
)

ADR_BASE_LISTENER = /home/oracle


# sqlnet.ora Network Configuration File: /home/oracle/db/product/12.1.0/dbhome_1/network/admin/sqlnet.ora
# Generated by Oracle configuration tools.

NAMES.DIRECTORY_PATH=(TNSNAMES, EZCONNECT)
ADR_BASE_LISTENER=/home/oracle


# tnsnames.ora Network Configuration File: /home/oracle/db/product/12.1.0/dbhome_1/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

LISTENER_ORCL =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.2.44)(PORT = 1521))


ORCL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.2.44)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orcl)
    )
  )



# 계정을 끄고 들어갈 때 ORA-01034: ORACLE not available 에러가 뜨면
sqlplus /nolog
conn sys /as sysdba
startup
# 이럼 될거임

# sath89/oracle-12c의 리스너 위치
# 계정/비밀번호 sys, system / oracle
# SID xe
docker exec -it oracle vi /u01/app/oracle-product/12.1.0/xe/network/admin/samples/listener.ora


ALTER USER tester IDENTIFIED BY "no1openbase"  REPLACE  "1234" ;

https://github.com/MaksymBilenko/docker-oracle-12c
https://github.com/MaksymBilenko/docker-oracle-12c/issues/116

http://studybug.tistory.com/166

https://www.oracle.com/ocom/groups/public/@otn/documents/webcontent/283698.htm

http://otsteam.tistory.com/284

#### SID 변경 ####
#1. 먼저 변경하고자하는 SID를 v$thread 로 확인한다.
sql>select instance from v$thread;

INSTANCE
----------------
xe
1 rowselected.  

#2. DB를shutdown한다. (shutdown normal or immediate)
#3. Fullbackup을 받는다.(All control, redo, data files backup)

#1) datafiles
sql>select file_name from dba_data_files;

FILE_NAME
----------------------------------------------------
/u01/app/oracle/oradata/xe/system01.dbf
/u01/app/oracle/oradata/xe/sysaux01.dbf
/u01/app/oracle/oradata/TESTFILE.DBF
/u01/app/oracle/oradata/xe/users01.dbf
/u01/app/oracle/oradata/xe/undotbs01.dbf

#2) redo logfiles
sql>select group#, member from v$logfile;
GROUP#     MEMBER
---------------------------------------------------
         1/u01/app/oracle/oradata/xe/redo01.log
         2/u01/app/oracle/oradata/xe/redo02.log
         3/u01/app/oracle/oradata/xe/redo03.log
3 rowsselected.                     

#3) controlfiles
sql>select name from v$controlfile;

NAME
----------------------------------------------------
/u01/app/oracle/oradata/xe/control01.ctl
/u01/app/oracle/fast_recovery_area/xe/control02.ctl
2 rowsselected.    

#4) fullbackup
sql> cp -r /u01/app/oracle/oradata/* /oracle/backup
cp -r /oracle/backup /u01/app/oracle/oradata

#4. .profile,.cshrc, .login, oratab, tnsnames.ora 파일에 ORACLE_SID가 설정되어있다면 이를 모두 새로운 ORACLE_SID명으로 변경시킨다.

OLDORACLE_SID : xe
NEWORACLE_SID: openbase

#5.$ORACLE_HOME/dbs directory에서 새로운 SID명을 사용하기 위해 다음 파일을 수정한다.

#1) initSID.ora 를 새로운 initSID.ora로 rename한다.

initxe.ora-> initopenbase.ora

#2) initSID.ora file의 ifile에 설정한 configuration parameters 파일도 rename한다.

configxe.ora-> contifopenbase.ora

#3) initSID.ora와 configSID.ora 파일에 예전 ORACLE_SID관련 사항이 있으면 새로운ORACLE_SID로 모두 변경한다. 예)initSID.ora

OLD)ifile=/u01/app/oracle/oradata/openbase/pfile/configxe.ora

NEW)ifile=/u01/app/oracle/oradata/openbase/pfile/configopenbase.ora

#6.Optional, 기존의SID명을 가진 data file이나 redo log file을 이용시 6번은 skip해도 된다. 만약 ORACLE_SID를 변경하면서 datafile이나 redo log file 이름도 새로운 SID명으로 함께 변경하려면 새로운 SID명의 디렉토리를 생성하여 mv로 기존 datafile과 redo logfile을 모두 옮긴뒤 alter 문으로 rename한다. 기존의/data/xe 에 있는 datafile과 redo log file을 새로운 SID명인 openbase디렉토리로 unix command 'mv'를 이용하여 모두 이동시킨다.
$data/xe>cd..
$data>mkdir openbase
$mv /u01/app/oracle/oradata/openbase/redo* /data/openbase
$mv /u01/app/oracle/oradata/openbase/system01.dbf /data/openbase
$mv /u01/app/oracle/oradata/openbase/rbs01.dbf /data/openbase
$mv /u01/app/oracle/oradata/openbase/tools01.dbf /data/openbase
$mv /u01/app/oracle/oradata/openbase/users01.dbf /data/openbase
$mv /u01/app/oracle/oradata/openbase/temp01.dbf /data/openbase

$sqll>

sql>startup mount
sql>alter database rename file '/u01/app/oracle/oradata/xe/redo01.log' to'/u01/app/oracle/oradata/openbase/redoOPENBASE01.log'
alter database rename file '/u01/app/oracle/oradata/xe/redo02.log' to'/u01/app/oracle/oradata/openbase/redoOPENBASE02.log'
alter database rename file '/u01/app/oracle/oradata/xe/redo03.log' to'/u01/app/oracle/oradata/openbase/redoOPENBASE03.log'
...

#7.$ORACLE_HOME/dbs 밑에 orapw<OLD_SID> 가 있으면 새로운 password file로 rename 작업을수행한다. 만약 orapw<OLD_SID>가 없으면 8번은 넘어간다. 새로운orapw<NEW_SID>를 생성하고 싶으면 아래 COMMAND를 이용한다.

orapwdfile=orapw<openbase password=no1openbase entries=<number of user to be

grantedpermission to start the database instance>

#8. db를startup하고 shutdown한 다음 full backup을 수행한다(backupcontrol, redo, data f iles).

#9. 변경된.profile을 적용하기 위해 다음을 수행한다.

$../.profile

# 또는

$exportORACLE_SID=openbase

# command를 수행한다.


#10. db를startup 한다.

#11. select instance from v$thread; 로 변경된ORACLE_SID를 확인한다.
sql>select instance from v$thread;

INSTANCE
----------------
openbase
1 rowselected.

#12. 기존에SID명이 기록되어있는 파일들을 수정한다.
$ORACLE_HOME/network/admin/listener.ora의 SID를 openbase 로 수정
$ORACLE_HOME/network/admin/tnsnames.ora의SID를 openbase 로 수정

Reference, http://1-day.tistory.com/9





#



# This file is used by ORACLE utilities.  It is created by root.sh
# and updated by either Database Configuration Assistant while creating
# a database or ASM Configuration Assistant while creating ASM instance.

# A colon, ':', is used as the field terminator.  A new line terminates
# the entry.  Lines beginning with a pound sign, '#', are comments.
#
# Entries are of the form:
#   $ORACLE_SID:$ORACLE_HOME:<N|Y>:
#
# The first and second fields are the system identifier and home
# directory of the database respectively.  The third field indicates
# to the dbstart utility that the database should , "Y", or should not,
# "N", be brought up at system boot time.
#
# Multiple entries with the same $ORACLE_SID are not allowed.
#
#
openbase:/u01/app/oracle/product/12.1.0/openbase:N
OPENBASE:/u01/app/oracle/product/12.1.0/OPENBASE:N


<alias>= [ (DESCRIPTION_LIST =  # Optional depending on whether u have
                                # one or more descriptions
                                # If there is just one description, unnecessary ]
          (DESCRIPTION=
            [ (SDU=2048) ]      # Optional, defaults to 2048
                                # Can take values between 512 and 32K
            [ (ADDRESS_LIST=    # Optional depending on whether u have
                                # one or more addresses
                                # If there is just one address, unnecessary ]
              (ADDRESS=
                [ (COMMUNITY=OPENBASELAB) ]
                (PROTOCOL=tcp)
                (HOST=192.168.2.45)
                (PORT=1521)
              )
              [ (ADDRESS=
                  (PROTOCOL=ipc)
                  (KEY=<ipckey (PNPKEY is a standard key used)>)
                )
              ]
              [ (ADDRESS=
                  [ (COMMUNITY=<community_name>) ]
                  (PROTOCOL=decnet)
                  (NODE=<nodename>)
                  (OBJECT=<objectname>)
                )
              ]
              ... # More addresses
            [ ) ] # Optional depending on whether ADDRESS_LIST is used or not
            [ (CONNECT_DATA=
                (SID=OPENBASE)
                [ (GLOBAL_NAME=OPENBASEDB) ]
              )
            ]
            [ (SOURCE_ROUTE=yes) ]
          )
          (DESCRIPTION=
            [ (SDU=2048) ]      # Optional, defaults to 2048
                                # Can take values between 512 and 32K
            [ (ADDRESS_LIST= ]  # Optional depending on whether u have more
                                # than one address or not
                                # If there is just one address, unnecessary
              (ADDRESS
                [ (COMMUNITY=<community_name>) ]
                (PROTOCOL=tcp)
                (HOST=<hostname>)
                (PORT=<portnumber (1521 is a standard port used)>)
              )
              [ (ADDRESS=
                  (PROTOCOL=ipc)
                  (KEY=<ipckey (PNPKEY is a standard key used)>)
                 )
              ]
              ...               # More addresses
            [ ) ]               # Optional depending on whether ADDRESS_LIST
                                # is being used
            [ (CONNECT_DATA=
                (SID=<oracle_sid>)
                [ (GLOBAL_NAME=<global_database_name>) ]
              )
            ]
            [ (SOURCE_ROUTE=yes) ]
          )
          [ (CONNECT_DATA=
              (SID=<oracle_sid>)
              [ (GLOBAL_NAME=<global_database_name>) ]
            )
          ]
          ...   # More descriptions
        [ ) ]   # Optional depending on whether DESCRIPTION_LIST is used or not